##
#    This code was generated by
#  ___ ___   _   ___ _  _    _____ _   _    _  ___   ___      _   ___ ___      ___   _   ___     ___ ___ _  _ ___ ___    _ _____ ___  ___ 
# | _ \ __| /_\ / __| || |__|_   _/_\ | |  | |/ | \ / / |    /_\ | _ ) __|___ / _ \ /_\ |_ _|__ / __| __| \| | __| _ \  /_\_   _/ _ \| _ \
# |   / _| / _ \ (__| __ |___|| |/ _ \| |__| ' < \ V /| |__ / _ \| _ \__ \___| (_) / _ \ | |___| (_ | _|| .` | _||   / / _ \| || (_) |   /
# |_|_\___/_/ \_\___|_||_|    |_/_/ \_\____|_|\_\ |_| |____/_/ \_\___/___/    \___/_/ \_\___|   \___|___|_|\_|___|_|_\/_/ \_\_| \___/|_|_\
# 
#    Reach Messaging API
#    Reach SMS API helps you add robust messaging capabilities to your applications.  Using this REST API, you can * send SMS messages * track the delivery of sent messages * schedule SMS messages to send at a later time * retrieve and modify message history
#
#    NOTE: This class is auto generated by OpenAPI Generator.
#    https://openapi-generator.tech
#    Do not edit the class manually.
#

module Reach
    module REST
        class Api
            class Messaging < Version
                ##
                # Initialize the Messaging version of Api
                def initialize(domain)
                    super
                    @version = 'rest'
                    @messaging_items = nil
                end

            
                ##
                # @param [String] message_id 
                # @return [Reach::REST::Api::Messaging::MessagingItemContext] if messageId was passed.
                # @return [Reach::REST::Api::Messaging::MessagingItemList]
                def messaging_items(message_id=:unset)
                    if message_id.nil?
                        raise ArgumentError, 'message_id cannot be nil'
                    end
                    if message_id == :unset
                        @messaging_items ||= MessagingItemList.new self
                    else
                        MessagingItemContext.new(self, message_id)
                    end
                end
                ##
                # Provide a user friendly representation
                def to_s
                    '<Reach::REST::Api::Messaging>';
                end
            end
        end
    end
end
